version: '3.8'
services:
  accounting-service:
    build:
      context: ./AccountingService
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/accounting_db
      - DATABASE_USERNAME=your_username
      - DATABASE_PASSWORD=your_password
  term-service:
    build:
      context: ./TermService
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/term_db
      - DATABASE_USERNAME=your_username
      - DATABASE_PASSWORD=your_password
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: accounting_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"