version: '3.8'
services:
  accounting-service:
    build:
      context: ./AccountingService
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/accounting_db
      - DATABASE_USERNAME=accoutingUser
      - DATABASE_PASSWORD=accoutingUser_pw_geheim
  term-service:
    build:
      context: ./TermService
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/term_db
      - DATABASE_USERNAME=termUser
      - DATABASE_PASSWORD=termUser_pw_geheim
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: accounting_db
      POSTGRES_USER: accoutingUser
      POSTGRES_PASSWORD: accoutingUser_pw_geheim
    ports:
      - "5432:5432"